# Generated by Django 6.0.3 on 2026-05-13 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', verbose_name='Message')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/', verbose_name='Fichier')),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio')], default='', max_length=10, verbose_name='Type de fichier')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='formations.group', verbose_name='Groupe')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message groupe',
                'verbose_name_plural': 'Messages groupe',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', verbose_name='Message')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/private/', verbose_name='Fichier')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message privé',
                'verbose_name_plural': 'Messages privés',
                'ordering': ['created_at'],
            },
        ),
    ]
