# Generated by Django 6.0.3 on 2026-05-29 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('client_title', models.CharField(blank=True, default='Cliente vérifiée', max_length=100, verbose_name='Titre / Rôle')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('comment', models.TextField(verbose_name='Commentaire / Avis')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Note (Étoiles)')),
                ('is_approved', models.BooleanField(default=False, verbose_name="Approuvé pour l'affichage")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Client (Optionnel)')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
