# Generated by Django 6.0.3 on 2026-06-01 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('has_received_welcome_coupon', models.BooleanField(default=False, verbose_name='A reçu le coupon de bienvenue')),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
